-- INSERT INTO child (id, firstname, lastname, parentemail, password, active)
-- VALUES (001, "Ella", "Jones", "michealjones@pmail.com", "Mjon123@", true),
--        (002, "Simbi", "Adeyemi", "sallyadeyimi@pmail.com", "@saL87L3!", true),
--        (003, "Brandon", "Alexander", "fionaaex@pmail.com", "0$Br71!!", true),
--        (004, "Akash", "Patel", "suneethapatel@pmail.com", "B3t%an1y", true);